export interface AuthenticatedUser {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  created_at: string;
  self_membership_id: number;
  description: string;
  interests: string;
  email_notifications: boolean;
  email_visible: boolean;
  last_login_at: string;
  total_route_distance: number;
  metric_units: boolean;
  hr_max: any | null;
  hr_rest: any | null;
  hr_zone_1_low: any | null;
  hr_zone_1_high: any | null;
  hr_zone_2_low: any | null;
  hr_zone_2_high: any | null;
  hr_zone_3_low: any | null;
  hr_zone_3_high: any | null;
  hr_zone_4_low: any | null;
  hr_zone_4_high: any | null;
  hr_zone_5_low: any | null;
  hr_zone_5_high: any | null;
  is_male: boolean;
  weight: number;
  vo2max: any | null;
  num_unread_messages: number;
  lat: number;
  lng: number;
  display_name: string | null;
  locality: string;
  administrative_area: string;
  postal_code: string;
  country_code: string;
  email_on_message: boolean;
  email_on_comment: boolean;
  email_on_update: boolean;
  visibility: number;
  time_zone: string;
  facebook_id: number | null;
  account_level: number;
  weeks_start_on: number;
  email_bounce_count: number;
  trips_included_in_totals_count: number;
  site_id: number;
  dob: string | null;
  deactivated: number;
  updated_at: string;
  deactivated_at: null;
  locale: string;
  name: string;
  age: number | null;
  privileges: any[];
  highlighted_photo_id: number;
  preferences: {
    metric_units: boolean;
    facebook: {
      notify_on_activity: boolean;
      notify_on_route: boolean;
    };
    route_planner_directions_type: string;
    receive_segment_notifications: boolean;
    date_format: string;
    segments_private: boolean;
    default_privacy_trip: number;
    default_privacy_route: number;
    calendar_show_hr: boolean;
    feeds_default_tab: string;
    default_career_interval: string;
    "planner-onboarding-dismissed": boolean;
    "realignment:dismissed": boolean;
    planner_overlay: string;
    show_dash_mini_onboarding: boolean;
    show_dash_onboarding_overlay: boolean;
    route_planner_right_sidebar_closed: boolean;
    route_planner_left_sidebar_closed: boolean;
    profile_default_tab: string;
    routes_grid_height: string;
    smart_export_file_format: string;
  };
  gear: {
    id: number;
    make: string;
    model: string;
    year: number;
    description: string;
    group_membership_id: number;
    gear_type_id: number | null;
    gear_model_id: number;
    created_at: string;
    exclude_from_totals: boolean;
    nickname: string;
    serial_number: string;
    weight: number;
    visibility: number;
    archived: boolean;
    use_user_timezone: boolean;
    project_529_id: number | null;
    name: string;
  }[];
  unseen_updates: any[];
  push_applications: any[];
  relevant_goal_participants: any[];
  club_ids: number[]; // number?
  slim_favorites: {
    id: number;
    associated_object_type: string;
    associated_object_id: number;
  }[];
  has_events: boolean;
  needs_password_reset: boolean;
  auth_token: string;
  user_summary: any | null;
}
