export interface BaseRide {
  id: number;
  group_membership_id: number;
  route_id: number | null;
  created_at: string;
  gear_id: number;
  departed_at: string;
  duration: number;
  distance: number;
  elevation_gain: number;
  elevation_loss: number;
  visibility: number;
  description: string | null;
  is_gps: boolean;
  name: string;
  max_hr: any | null;
  min_hr: any | null;
  avg_hr: any | null;
  max_cad: any | null;
  min_cad: any | null;
  avg_cad: any | null;
  avg_speed: number;
  max_speed: number;
  moving_time: number;
  processed: boolean;
  avg_watts: any | null;
  max_watts: any | null;
  min_watts: any | null;
  is_stationary: boolean;
  calories: number;
  updated_at: string;
  time_zone: string;
  first_lng: number;
  first_lat: number;
  last_lng: number;
  last_lat: number;
  user_id: number;
  deleted_at: string | null;
  sw_lng: number;
  sw_lat: number;
  ne_lng: number;
  ne_lat: number;
  track_id: string;
  postal_code: any | null;
  locality: string;
  administrative_area: string;
  country_code: string;
  highlighted_photo_id: number;
  utc_offset: number;
}
